// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJjNdSkhGDnuGLiHFXK3NQzyYjOjOM2c',
    appId: '1:735287171844:android:8dde0c1a824af925c70e51',
    messagingSenderId: '735287171844',
    projectId: 'zehraapp-2cdcb',
    storageBucket: 'zehraapp-2cdcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG40mai50DgSRr5ZHQEsdEMFI3iAscf8w',
    appId: '1:735287171844:ios:f7504c9c8e90c85dc70e51',
    messagingSenderId: '735287171844',
    projectId: 'zehraapp-2cdcb',
    storageBucket: 'zehraapp-2cdcb.appspot.com',
    androidClientId: '735287171844-iurauvf1kn6bkemraoqopiu4isjn0480.apps.googleusercontent.com',
    iosClientId: '735287171844-fartadscm9rtgp3c93hn7qnk2too36ut.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
